<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260603222246 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE order_status_history (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, old_status VARCHAR(50) NOT NULL, changed_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, order_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_471AD77E8D9F6D38 ON order_status_history (order_id)');
        $this->addSql('CREATE TABLE system_log (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, action VARCHAR(100) NOT NULL, details TEXT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, uset_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_4287C21E82058C49 ON system_log (uset_id)');
        $this->addSql('ALTER TABLE order_status_history ADD CONSTRAINT FK_471AD77E8D9F6D38 FOREIGN KEY (order_id) REFERENCES "order" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE system_log ADD CONSTRAINT FK_4287C21E82058C49 FOREIGN KEY (uset_id) REFERENCES usuario (id)');
        $this->addSql('ALTER TABLE order_document ADD order_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE order_document ADD CONSTRAINT FK_399168C78D9F6D38 FOREIGN KEY (order_id) REFERENCES "order" (id)');
        $this->addSql('CREATE INDEX IDX_399168C78D9F6D38 ON order_document (order_id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE order_status_history DROP CONSTRAINT FK_471AD77E8D9F6D38');
        $this->addSql('ALTER TABLE system_log DROP CONSTRAINT FK_4287C21E82058C49');
        $this->addSql('DROP TABLE order_status_history');
        $this->addSql('DROP TABLE system_log');
        $this->addSql('ALTER TABLE order_document DROP CONSTRAINT FK_399168C78D9F6D38');
        $this->addSql('DROP INDEX IDX_399168C78D9F6D38');
        $this->addSql('ALTER TABLE order_document DROP order_id');
    }
}
