<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260610214635 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE "order" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, number VARCHAR(50) NOT NULL, customer_name VARCHAR(255) NOT NULL, customer_email VARCHAR(255) NOT NULL, total_amount NUMERIC(10, 2) NOT NULL, status VARCHAR(50) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE order_document (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, original_name VARCHAR(255) NOT NULL, file_path VARCHAR(500) NOT NULL, mime_type VARCHAR(100) NOT NULL, uploaded_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, order_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_399168C78D9F6D38 ON order_document (order_id)');
        $this->addSql('CREATE TABLE order_status_history (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, old_status VARCHAR(50) NOT NULL, new_status VARCHAR(50) NOT NULL, changed_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, order_id INT NOT NULL, changed_by_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_471AD77E8D9F6D38 ON order_status_history (order_id)');
        $this->addSql('CREATE INDEX IDX_471AD77E828AD0A0 ON order_status_history (changed_by_id)');
        $this->addSql('CREATE TABLE system_log (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, action VARCHAR(100) NOT NULL, details TEXT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, usuario_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_4287C21EDB38439E ON system_log (usuario_id)');
        $this->addSql('CREATE TABLE usuario (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nome VARCHAR(255) NOT NULL, email VARCHAR(255) NOT NULL, senha VARCHAR(255) NOT NULL, ativo BOOLEAN NOT NULL, perfil VARCHAR(50) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_2265B05DE7927C74 ON usuario (email)');
        $this->addSql('ALTER TABLE order_document ADD CONSTRAINT FK_399168C78D9F6D38 FOREIGN KEY (order_id) REFERENCES "order" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE order_status_history ADD CONSTRAINT FK_471AD77E8D9F6D38 FOREIGN KEY (order_id) REFERENCES "order" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE order_status_history ADD CONSTRAINT FK_471AD77E828AD0A0 FOREIGN KEY (changed_by_id) REFERENCES usuario (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE system_log ADD CONSTRAINT FK_4287C21EDB38439E FOREIGN KEY (usuario_id) REFERENCES usuario (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE order_document DROP CONSTRAINT FK_399168C78D9F6D38');
        $this->addSql('ALTER TABLE order_status_history DROP CONSTRAINT FK_471AD77E8D9F6D38');
        $this->addSql('ALTER TABLE order_status_history DROP CONSTRAINT FK_471AD77E828AD0A0');
        $this->addSql('ALTER TABLE system_log DROP CONSTRAINT FK_4287C21EDB38439E');
        $this->addSql('DROP TABLE "order"');
        $this->addSql('DROP TABLE order_document');
        $this->addSql('DROP TABLE order_status_history');
        $this->addSql('DROP TABLE system_log');
        $this->addSql('DROP TABLE usuario');
    }
}
