<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260603224108 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE "user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, role VARCHAR(50) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('ALTER TABLE order_status_history ADD changed_by_id INT NOT NULL');
        $this->addSql('ALTER TABLE order_status_history ADD CONSTRAINT FK_471AD77E828AD0A0 FOREIGN KEY (changed_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('CREATE INDEX IDX_471AD77E828AD0A0 ON order_status_history (changed_by_id)');
        $this->addSql('ALTER TABLE system_log DROP CONSTRAINT fk_4287c21e82058c49');
        $this->addSql('DROP INDEX idx_4287c21e82058c49');
        $this->addSql('ALTER TABLE system_log RENAME COLUMN uset_id TO user_id');
        $this->addSql('ALTER TABLE system_log ADD CONSTRAINT FK_4287C21EA76ED395 FOREIGN KEY (user_id) REFERENCES usuario (id)');
        $this->addSql('CREATE INDEX IDX_4287C21EA76ED395 ON system_log (user_id)');
        $this->addSql('ALTER TABLE usuario RENAME COLUMN senha TO password');
        $this->addSql('ALTER TABLE usuario RENAME COLUMN ativo TO active');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE "user"');
        $this->addSql('ALTER TABLE order_status_history DROP CONSTRAINT FK_471AD77E828AD0A0');
        $this->addSql('DROP INDEX IDX_471AD77E828AD0A0');
        $this->addSql('ALTER TABLE order_status_history DROP changed_by_id');
        $this->addSql('ALTER TABLE system_log DROP CONSTRAINT FK_4287C21EA76ED395');
        $this->addSql('DROP INDEX IDX_4287C21EA76ED395');
        $this->addSql('ALTER TABLE system_log RENAME COLUMN user_id TO uset_id');
        $this->addSql('ALTER TABLE system_log ADD CONSTRAINT fk_4287c21e82058c49 FOREIGN KEY (uset_id) REFERENCES usuario (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX idx_4287c21e82058c49 ON system_log (uset_id)');
        $this->addSql('ALTER TABLE usuario RENAME COLUMN password TO senha');
        $this->addSql('ALTER TABLE usuario RENAME COLUMN active TO ativo');
    }
}
